class bank:
    def __init__(self):
        self.acNo=int(input())
        self.name=input()
        self.tOfacc=input()
        self.bal=int(input())
        self.depAm=int(input())
        self.wiAm=int(input())
        print("Enter Details:")
        print("Account No.")
        print("Name:")
        print("Account Type:")
        print("Balance:")
        print("Enter Deposit Amount =")
        print("Enter Withdraw Amount =")
        print(f"Account No.: {self.acNo}")
        print(f"Name: {self.name}")
        print(f"Account Type: {self.tOfacc}")
        print(f"Balance: {float(self.bal+self.depAm-self.wiAm)}")
ob=bank()